/** Static UI shell only. Server data is always assigned through textContent. */
export function localChatWidget(openChat: boolean, customerId: string) {
  return `(function(){
var root=document.createElement('section'),open=false,timer,pendingEventId,pendingBody;
root.className='local-chat';root.setAttribute('aria-label','Support chat');
root.innerHTML='<button class="local-chat-launcher" type="button" aria-expanded="false">Chat with support</button><div class="local-chat-panel" hidden><div class="local-chat-header"><strong>Support</strong><button type="button" aria-label="Close chat">×</button></div><div class="local-chat-messages" aria-live="polite"></div><p class="local-chat-status" aria-live="polite"></p><form class="local-chat-form"><label>Message<textarea required maxlength="10000" rows="3"></textarea></label><p class="local-chat-error" role="alert"></p><button type="submit">Send</button></form></div>';
document.body.append(root);
var launch=root.querySelector('.local-chat-launcher'),panel=root.querySelector('.local-chat-panel'),close=root.querySelector('.local-chat-header button'),messages=root.querySelector('.local-chat-messages'),status=root.querySelector('.local-chat-status'),form=root.querySelector('form'),area=root.querySelector('textarea'),submit=root.querySelector('.local-chat-form button'),error=root.querySelector('.local-chat-error'),customerId=${JSON.stringify(customerId)};
function add(message){var row=document.createElement('p');row.className='local-chat-message '+(message.author==='customer'?'mine':'theirs');row.textContent=message.body;messages.append(row)}
function clear(){messages.replaceChildren();location.assign('/entrar')}
function history(){return fetch('/chat/history',{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok){if(r.status===401)clear();throw Error(r.status===401?'Session expired.':'Chat history is unavailable.')}return r.json()}).then(function(data){if(data.customerId!==customerId){clear();return}messages.replaceChildren();data.messages.forEach(add);status.textContent=data.status?('Request status: '+data.status.replace('_',' ')):''}).catch(function(e){error.textContent=e.message})}
function check(){fetch('/sessao',{credentials:'same-origin',cache:'no-store'}).then(function(r){if(!r.ok)return clear();return r.json()}).then(function(session){if(session&&session.customerId!==customerId)clear()}).catch(function(){})}
function show(){open=true;panel.hidden=false;launch.setAttribute('aria-expanded','true');area.focus();history();timer=setInterval(function(){if(!document.hidden)history()},5000)}
function hide(){open=false;panel.hidden=true;launch.setAttribute('aria-expanded','false');clearInterval(timer);launch.focus()}
launch.addEventListener('click',function(){open?hide():show()});close.addEventListener('click',hide);document.addEventListener('keydown',function(e){if(e.key==='Escape'&&open)hide()});
form.addEventListener('submit',function(e){e.preventDefault();var body=area.value.trim();if(!body)return;if(pendingBody&&pendingBody!==body)pendingEventId=undefined;pendingBody=body;pendingEventId=pendingEventId||crypto.randomUUID();error.textContent='';area.disabled=true;submit.disabled=true;fetch('/chat/messages',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-csrf-token':document.querySelector('input[name=csrf]').value},body:JSON.stringify({body:body,eventId:pendingEventId})}).then(function(r){if(!r.ok)return r.json().then(function(v){throw Error(v.error||'Message failed.')});pendingEventId=undefined;pendingBody=undefined;area.value='';return history()}).catch(function(e){error.textContent=e.message}).finally(function(){area.disabled=false;submit.disabled=false;area.focus()})});
setInterval(check,5000);window.addEventListener('visibilitychange',function(){if(!document.hidden)check()});if(${JSON.stringify(openChat)})show();})();`;
}
