export const Colors = {
  accent1: 'var(--accent1)',
  accent2: 'var(--accent2)',
  accent3: 'var(--accent3)',
  accent5: 'var(--accent5)',
  accent6: 'var(--accent6)',
  accent1Dark: 'var(--accent1Dark)',
  accent2Dark: 'var(--accent2Dark)',
  accent3Dark: 'var(--accent3Dark)',
  accent5Dark: 'var(--accent5Dark)',
  accent6Dark: 'var(--accent6Dark)',
  accent1Darker: 'var(--accent1Darker)',
  accent2Darker: 'var(--accent2Darker)',
  accent3Darker: 'var(--accent3Darker)',
  accent5Darker: 'var(--accent5Darker)',
  accent6Darker: 'var(--accent6Darker)',
  neutral1: 'var(--neutral1)',
  neutral2: 'var(--neutral2)',
  neutral3: 'var(--neutral3)',
  neutral4: 'var(--neutral4)',
  neutral5: 'var(--neutral5)',
  neutral6: 'var(--neutral6)',
  background: 'var(--background)',
  sidebar: 'var(--sidebar)',
  card: 'var(--card)',
  popover: 'var(--popover)',
  'surface-panel': 'var(--surface-panel)',
  'surface-overlay-soft': 'var(--surface-overlay-soft)',
  'surface-overlay-strong': 'var(--surface-overlay-strong)',
  'fill-subtle': 'var(--fill-subtle)',
  fill: 'var(--fill)',
  'fill-hover': 'var(--fill-hover)',
  'fill-active': 'var(--fill-active)',
  'fill-strong': 'var(--fill-strong)',
  muted: 'var(--muted)',
  foreground: 'var(--foreground)',
  'muted-foreground': 'var(--muted-foreground)',
  placeholder: 'var(--placeholder)',
  ring: 'var(--ring)',
  destructive: 'var(--destructive)',
  'destructive-foreground': 'var(--destructive-foreground)',

  error: 'var(--error)',

  scrim: 'var(--scrim)',

  text1: 'var(--text1)',
  warning1: 'var(--warning1)',
  positive1: 'var(--positive1)',
  negative1: 'var(--negative1)',

  'notice-success': 'var(--notice-success)',
  'notice-success-fg': 'var(--notice-success-fg)',
  'notice-destructive': 'var(--notice-destructive)',
  'notice-destructive-fg': 'var(--notice-destructive-fg)',
  'notice-warning': 'var(--notice-warning)',
  'notice-warning-fg': 'var(--notice-warning-fg)',
  'notice-info': 'var(--notice-info)',
  'notice-info-fg': 'var(--notice-info-fg)',
  'notice-note': 'var(--notice-note)',
  'notice-note-fg': 'var(--notice-note-fg)',

  'badge-neutral-fg': 'var(--badge-neutral-fg)',
  'badge-green': 'var(--badge-green)',
  'badge-green-fg': 'var(--badge-green-fg)',
  'badge-red': 'var(--badge-red)',
  'badge-red-fg': 'var(--badge-red-fg)',
  'badge-blue': 'var(--badge-blue)',
  'badge-blue-fg': 'var(--badge-blue-fg)',
  'badge-yellow': 'var(--badge-yellow)',
  'badge-yellow-fg': 'var(--badge-yellow-fg)',
  'badge-purple': 'var(--badge-purple)',
  'badge-purple-fg': 'var(--badge-purple-fg)',
  'badge-orange': 'var(--badge-orange)',
  'badge-orange-fg': 'var(--badge-orange-fg)',
  'badge-cyan': 'var(--badge-cyan)',
  'badge-cyan-fg': 'var(--badge-cyan-fg)',
  'badge-pink': 'var(--badge-pink)',
  'badge-pink-fg': 'var(--badge-pink-fg)',

  'green-50': 'var(--brand-green-50)',
  'green-100': 'var(--brand-green-100)',
  'green-200': 'var(--brand-green-200)',
  'green-300': 'var(--brand-green-300)',
  'green-400': 'var(--brand-green-400)',
  'green-500': 'var(--brand-green-500)',
  'green-600': 'var(--brand-green-600)',
  'green-700': 'var(--brand-green-700)',
  'green-800': 'var(--brand-green-800)',
  'green-900': 'var(--brand-green-900)',
  'green-950': 'var(--brand-green-950)',
};

export const BorderColors = {
  border: 'var(--border)',
  'border-strong': 'var(--border-strong)',
  'border-hover': 'var(--border-hover)',
  'border-focus': 'var(--border-focus)',
};

export const CHART_LABEL_COLOR = 'var(--muted-foreground)';
