export const configurationDefaults = Object.freeze({
  environment: 'demo-default' as const,
  tenantId: 'demo',
  jurisdiction: 'US' as const,
  policyProfile: 'demo-default' as const,
  piiMode: 'demo-default' as const,
  locale: 'en-US',
  openapiPath: '/openapi.json',
  documentExtractionProvider: 'fixture',
  documentExtractionModel: 'fixture',
  openAiExtractionInputUsdPerMillion: 0.2,
  openAiExtractionOutputUsdPerMillion: 1.2,
  openAiExtractionPriceVersion: 'openai-gpt-5.6-luna-2026-08-22',
  kycAgentModel: 'openai-gpt-5.6-luna',
  identityVerificationProvider: 'local-identity',
  addressVerificationProvider: 'local-address',
  sanctionsScreeningProvider: 'fixture-sanctions',
  pepScreeningProvider: 'fixture-pep',
  documentStorageProvider: 'local-filesystem',
  notificationProvider: 'local-inbox',
  webhookPublisher: 'capture',
  provisioningProvider: 'simulated',
  riskPolicyProvider: 'demo-default@1.1.0',
  riskAssessmentProvider: 'rule-based' as const,
  riskAssessmentModel: 'openai-gpt-5.6-luna',
  providerTimeoutMs: 10_000,
  providerMaxAttempts: 3,
  providerRetryBaseDelayMs: 100,
});
