import { describe, it, expect } from 'vitest';
import { z } from 'zod';
import { parseSchema, CustomZodProvider } from '../index';

describe('CustomZodProvider.validateSchema', () => {
  it('preserves Date values while stripping empty strings', () => {
    const provider = new CustomZodProvider(
      z.object({
        startDate: z.date(),
        name: z.string().optional(),
      }),
    );
    const startDate = new Date('2024-01-01T00:00:00Z');

    const result = provider.validateSchema({ startDate, name: '' });

    expect(result).toEqual({ success: true, data: { startDate } });
  });

  describe('when an optional object group has no child values', () => {
    it('omits the empty group generated by schema defaults', () => {
      const provider = new CustomZodProvider(z.object({ options: z.object({ limit: z.number() }).optional() }));

      expect(provider.validateSchema(provider.getDefaultValues())).toEqual({ success: true, data: {} });
    });

    it('omits a group containing an undefined registered child', () => {
      const provider = new CustomZodProvider(z.object({ options: z.object({ limit: z.number() }).optional() }));

      expect(provider.validateSchema({ options: { limit: undefined } })).toEqual({ success: true, data: {} });
    });
  });

  describe('when an empty object group is required', () => {
    it('reports the missing child instead of omitting the group', () => {
      const provider = new CustomZodProvider(z.object({ options: z.object({ limit: z.number() }) }));

      expect(provider.validateSchema({ options: {} })).toEqual({
        success: false,
        errors: [expect.objectContaining({ path: ['options', 'limit'] })],
      });
    });
  });

  describe('when an optional object group contains an invalid child', () => {
    it('rejects a blank child when another child is populated', () => {
      const provider = new CustomZodProvider(
        z.object({ options: z.object({ limit: z.number(), label: z.string().optional() }).optional() }),
      );

      expect(provider.validateSchema({ options: { limit: '', label: 'Populated' } })).toEqual({
        success: false,
        errors: [expect.objectContaining({ path: ['options', 'limit'] })],
      });
    });

    it('rejects a nonempty invalid child instead of omitting the group', () => {
      const provider = new CustomZodProvider(z.object({ options: z.object({ limit: z.number() }).optional() }));

      expect(provider.validateSchema({ options: { limit: 'invalid' } })).toEqual({
        success: false,
        errors: [expect.objectContaining({ path: ['options', 'limit'] })],
      });
    });
  });

  describe('when an empty object would restore a group default', () => {
    it('reports the missing child instead of restoring the cleared default', () => {
      const provider = new CustomZodProvider(
        z.object({ options: z.object({ limit: z.number() }).default({ limit: 10 }) }),
      );

      expect(provider.validateSchema({ options: {} })).toEqual({
        success: false,
        errors: [expect.objectContaining({ path: ['options', 'limit'] })],
      });
    });
  });

  describe('when an array contains an incomplete item', () => {
    it('rejects that item without silently dropping it or moving the error to another index', () => {
      const provider = new CustomZodProvider(z.object({ documents: z.array(z.object({ title: z.string().min(1) })) }));

      const result = provider.validateSchema({ documents: [{ title: '' }, { title: 'Keep me' }] });

      expect(result).toEqual({
        success: false,
        errors: [expect.objectContaining({ path: ['documents', 0, 'title'] })],
      });
    });
  });

  describe('when explicit empty values satisfy the schema', () => {
    it('preserves empty collections, cleared defaults, and nullable values', () => {
      const provider = new CustomZodProvider(
        z.object({
          documents: z.array(z.string()),
          options: z.object({}).optional(),
          note: z.string().default('Default note'),
          choice: z.string().nullable().optional(),
        }),
      );
      const input = { documents: [], options: {}, note: '', choice: null };

      expect(provider.validateSchema(input)).toEqual({ success: true, data: input });
    });
  });

  describe('when a required text field is left blank', () => {
    it('reports it as missing instead of submitting an empty string', () => {
      const provider = new CustomZodProvider(
        z.object({ note: z.string(), details: z.object({ label: z.string() }).optional() }),
      );

      expect(provider.validateSchema({ note: '', details: { label: '' } })).toEqual({
        success: false,
        errors: [{ path: ['note'], message: 'Required' }],
      });
    });
  });

  describe('when a record entry is left blank', () => {
    it('omits the entry instead of rejecting the blank string', () => {
      const provider = new CustomZodProvider(z.object({ limits: z.record(z.string(), z.number().optional()) }));

      expect(provider.validateSchema({ limits: { threshold: '', retries: 3 } })).toEqual({
        success: true,
        data: { limits: { retries: 3 } },
      });
    });
  });

  describe('when an array item has a cleared default', () => {
    it('submits the cleared value rather than restoring the nested default', () => {
      const provider = new CustomZodProvider(
        z.object({ documents: z.array(z.object({ title: z.string().default('Default title') })) }),
      );
      const input = { documents: [{ title: '' }] };

      expect(provider.validateSchema(input)).toEqual({ success: true, data: input });
    });
  });
  describe('when a union option has a blank optional field', () => {
    it('normalizes that field before the union picks an option', () => {
      const provider = new CustomZodProvider(
        z.object({
          target: z.union([z.object({ limit: z.number().optional() }), z.object({ name: z.string().min(1) })]),
        }),
      );

      expect(provider.validateSchema({ target: { limit: '', name: '' } })).toEqual({
        success: true,
        data: { target: {} },
      });
    });
  });

  describe('when an optional union group is left blank', () => {
    it('omits the group', () => {
      const provider = new CustomZodProvider(
        z.object({
          target: z.union([z.object({ a: z.string().min(1) }), z.object({ b: z.string().min(1) })]).optional(),
        }),
      );

      expect(provider.validateSchema({ target: { a: '', b: '' } })).toEqual({ success: true, data: {} });
    });
  });

  describe('when an intersection side has a blank optional field', () => {
    it('normalizes both sides before validating', () => {
      const provider = new CustomZodProvider(
        z.object({
          target: z.intersection(z.object({ id: z.string() }), z.object({ limit: z.number().optional() })),
        }),
      );

      expect(provider.validateSchema({ target: { id: 'a', limit: '' } })).toEqual({
        success: true,
        data: { target: { id: 'a' } },
      });
    });
  });
});

describe('parseSchema v4Type fallback — array fields', () => {
  it('should detect z.array(z.string()) as type "array" with element subSchema', () => {
    const schema = z.object({
      items: z.array(z.string()),
    });

    const result = parseSchema(schema);
    const itemsField = result.fields.find(f => f.key === 'items');

    expect(itemsField).toBeDefined();
    expect(itemsField!.type).toBe('array');
    expect(itemsField!.schema).toHaveLength(1);
    expect(itemsField!.schema![0]!.type).toBe('string');
    expect(itemsField!.schema![0]!.key).toBe('0');
  });

  it('should detect z.array(z.number()) as type "array" with number element', () => {
    const schema = z.object({
      nums: z.array(z.number()),
    });

    const result = parseSchema(schema);
    const numsField = result.fields.find(f => f.key === 'nums');

    expect(numsField!.type).toBe('array');
    expect(numsField!.schema).toHaveLength(1);
    expect(numsField!.schema![0]!.type).toBe('number');
  });

  it('should detect z.array(z.object(...)) as type "array" with object element', () => {
    const schema = z.object({
      sources: z.array(
        z.object({
          title: z.string(),
          url: z.string(),
        }),
      ),
    });

    const result = parseSchema(schema);
    const sourcesField = result.fields.find(f => f.key === 'sources');

    expect(sourcesField!.type).toBe('array');
    expect(sourcesField!.schema).toHaveLength(1);
    expect(sourcesField!.schema![0]!.type).toBe('object');
  });

  it('should handle array fields with .min()/.max() constraints', () => {
    const schema = z.object({
      items: z.array(z.string()).min(1).max(10),
    });

    const result = parseSchema(schema);
    const itemsField = result.fields.find(f => f.key === 'items');

    expect(itemsField!.type).toBe('array');
    expect(itemsField!.schema).toHaveLength(1);
  });
});

describe('parseSchema v4Type fallback — union fields', () => {
  it('should detect z.union([z.string(), z.number()]) as type "union"', () => {
    const schema = z.object({
      value: z.union([z.string(), z.number()]),
    });

    const result = parseSchema(schema);
    const valueField = result.fields.find(f => f.key === 'value');

    expect(valueField).toBeDefined();
    expect(valueField!.type).toBe('union');
    expect(valueField!.schema!.length).toBe(2);
  });
});

describe('parseSchema — primitive fields (control)', () => {
  it('should correctly parse string, number, and boolean fields', () => {
    const schema = z.object({
      name: z.string(),
      age: z.number(),
      active: z.boolean(),
    });

    const result = parseSchema(schema);
    expect(result.fields).toHaveLength(3);
    expect(result.fields.find(f => f.key === 'name')!.type).toBe('string');
    expect(result.fields.find(f => f.key === 'age')!.type).toBe('number');
    expect(result.fields.find(f => f.key === 'active')!.type).toBe('boolean');
  });
});
