// This file is auto-generated by @hey-api/openapi-ts

export const SessionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    }
} as const;

export const CustomHttpAgentSchema = {
    type: 'object',
    properties: {
        'session-id': {
            type: 'string'
        },
        'enable-proxy': {
            type: 'string'
        }
    }
} as const;