// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type { PostWebdriverData, PostWebdriverError, PostWebdriverResponse, GetConnectError, GetConnectResponse, GetV1SessionsBySessionIdData, GetV1SessionsBySessionIdError, GetV1SessionsBySessionIdResponse, GetReferenceApiConnectError, GetReferenceApiConnectResponse, GetReferenceApiListAllSessionsError, GetReferenceApiListAllSessionsResponse, PostReferenceApiUploadAnExtensionError, PostReferenceApiUploadAnExtensionResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create a session
 */
export const postWebdriver = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<PostWebdriverData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostWebdriverResponse, PostWebdriverError, ThrowOnError>({
        ...options,
        url: '/webdriver'
    });
};

/**
 * Connect to a session
 */
export const getConnect = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetConnectResponse, GetConnectError, ThrowOnError>({
        ...options,
        url: '/connect'
    });
};

/**
 * Retrieve information from a Session
 * Use this endpoint to get information from a specific Session.
 */
export const getV1SessionsBySessionId = <ThrowOnError extends boolean = false>(options: OptionsLegacyParser<GetV1SessionsBySessionIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1SessionsBySessionIdResponse, GetV1SessionsBySessionIdError, ThrowOnError>({
        ...options,
        url: '/v1/sessions/{sessionId}'
    });
};

/**
 * Connect to a Session
 * Use WebSocket or HTTP to connect or create a Session on-the-fly
 */
export const getReferenceApiConnect = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetReferenceApiConnectResponse, GetReferenceApiConnectError, ThrowOnError>({
        ...options,
        url: '/reference/api/connect'
    });
};

/**
 * List all Sessions
 * Get full control of the Browser’s Sessions
 */
export const getReferenceApiListAllSessions = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetReferenceApiListAllSessionsResponse, GetReferenceApiListAllSessionsError, ThrowOnError>({
        ...options,
        url: '/reference/api/list-all-sessions'
    });
};

/**
 * Upload a Chrome extension
 * Configure custom Chrome extensions for your Sessions
 */
export const postReferenceApiUploadAnExtension = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<PostReferenceApiUploadAnExtensionResponse, PostReferenceApiUploadAnExtensionError, ThrowOnError>({
        ...options,
        url: '/reference/api/upload-an-extension'
    });
};