// This file is auto-generated by @hey-api/openapi-ts

export type PostWebdriverData = {
    body?: {
        projectId?: string;
    };
};

export type PostWebdriverResponse = (unknown);

export type PostWebdriverError = unknown;

export type GetConnectResponse = (unknown);

export type GetConnectError = unknown;

export type GetV1SessionsBySessionIdData = {
    path: {
        /**
         * ID of the Session to retrieve information from
         */
        sessionId: string;
    };
};

export type GetV1SessionsBySessionIdResponse = ({
    [key: string]: unknown;
});

export type GetV1SessionsBySessionIdError = unknown;

export type GetReferenceApiConnectResponse = (unknown);

export type GetReferenceApiConnectError = unknown;

export type GetReferenceApiListAllSessionsResponse = (unknown);

export type GetReferenceApiListAllSessionsError = unknown;

export type PostReferenceApiUploadAnExtensionResponse = (unknown);

export type PostReferenceApiUploadAnExtensionError = unknown;