import { z } from 'zod';

export const reasonCodeSchema = z.enum([
  'COMPLETENESS_REQUIRED_DOCUMENT_MISSING',
  'COMPLETENESS_REQUIRED_DOCUMENT_SIDE_MISSING',
  'COMPLETENESS_REQUIRED_FIELD_MISSING',
  'COMPLETENESS_FIELD_CONFIDENCE_LOW',
  'COMPLETENESS_DOCUMENT_UNREADABLE',
  'COMPLETENESS_MISSING_INFORMATION_ROUND_LIMIT',
  'EVIDENCE_COMPLETE',
  'EVIDENCE_DUPLICATE',
  'EVIDENCE_INCOMPLETE',
  'EVIDENCE_REQUIRED_CHECK_UNAVAILABLE',
  'RISK_IDENTITY_MATCH',
  'RISK_IDENTITY_MISMATCH',
  'RISK_IDENTITY_INCONCLUSIVE',
  'RISK_ADDRESS_MATCH',
  'RISK_ADDRESS_MISMATCH',
  'RISK_ADDRESS_INCONCLUSIVE',
  'RISK_SANCTIONS_CLEAR',
  'RISK_SANCTIONS_POSSIBLE',
  'RISK_SANCTIONS_STRONG',
  'RISK_PEP_CLEAR',
  'RISK_PEP_POSSIBLE',
  'RISK_PEP_STRONG',
  'RISK_POLICY_AUTO_REVIEW',
  'RISK_POLICY_REJECT_RECOMMENDED',
  'RISK_POLICY_ESCALATE_RECOMMENDED',
  'RISK_POLICY_INSUFFICIENT_INFORMATION',
  'REVIEW_APPROVED',
  'REVIEW_REJECTED',
  'REVIEW_ESCALATED',
  'REVIEW_INSUFFICIENT_AUTHORITY',
  'REVIEW_DUPLICATE',
  'REVIEW_CONFLICT',
  'REVIEW_EXPIRED',
  'PROVISIONING_ACCOUNT_PROVISIONED',
  'PROVISIONING_ACCOUNT_PROVISIONING_FAILED',
]);

export const reasonTaxonomyVersionSchema = z.literal('1.0.0');

export type ReasonCode = z.infer<typeof reasonCodeSchema>;
