import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { Command } from 'commander';
import { format } from 'oxfmt';
import type { FormatConfig } from 'oxfmt';

import { API_COMMANDS, registerApiCommand } from '../src/commands/api/index.js';
import type { ApiCommandDescriptor } from '../src/commands/api/types.js';

export const outputPath = path.resolve(import.meta.dirname, '../../mcp/src/server/mastra-api-operations.generated.ts');

export function isApiPrefixedCommand(command: Pick<ApiCommandDescriptor, 'routePlacement'>): boolean {
  return (command.routePlacement ?? 'api-prefix') === 'api-prefix';
}

export function getOperations() {
  registerApiCommand(new Command());

  // The MCP requester supports API-prefixed server routes, not origin-relative Factory/platform routes.
  return Object.values(API_COMMANDS)
    .filter(isApiPrefixedCommand)
    .map(command => ({
      name: command.name.replaceAll(' ', '_').replaceAll('-', '_'),
      description: command.description,
      method: command.method,
      path: command.path,
      ...(command.verbose ? { verbosePath: command.verbose.path } : {}),
      destructive: command.method !== 'GET',
    }));
}

export async function generateOperationsSource() {
  const output = `// This file is generated by packages/cli/scripts/generate-mcp-api-operations.ts. Do not edit by hand.
// Scope: API-prefixed Mastra server CLI commands only; origin-relative Factory/platform commands are excluded.

export const MASTRA_API_OPERATIONS = ${JSON.stringify(getOperations(), null, 2)} as const;
`;
  const config = JSON.parse(
    await readFile(path.resolve(import.meta.dirname, '../../../.oxfmtrc.json'), 'utf8'),
  ) as FormatConfig;
  const result = await format(outputPath, output, config);
  if (result.errors.length > 0) {
    throw new Error(`Failed to format MCP API operations: ${JSON.stringify(result.errors)}`);
  }
  return result.code;
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  await writeFile(outputPath, await generateOperationsSource());
}
